-- Basecamp initial schema: HealthKit workout ingest (summary + chunked track).

create table workout (
    id                       uuid             primary key,
    healthkit_uuid           uuid             not null unique,
    type                     text,
    start_date               timestamptz,
    end_date                 timestamptz,
    duration_seconds         double precision not null,
    distance_m               double precision,
    elevation_gain_m         double precision,
    elevation_loss_m         double precision,
    active_calories          double precision,
    basal_calories           double precision,
    route_point_count        integer          not null,
    content_hash             text,
    source_name              text,
    source_bundle_id         text,
    source_version           text,
    device_name              text,
    device_model             text,
    device_manufacturer      text,
    device_hardware_version  text,
    device_software_version  text,
    metadata                 jsonb,
    track_status             text             not null,
    expected_chunks          integer,
    created_at               timestamptz      not null,
    updated_at               timestamptz      not null
);

create table workout_statistic (
    workout_id  uuid             not null references workout (id) on delete cascade,
    name        text             not null,
    min         double precision not null,
    max         double precision not null,
    avg         double precision not null,
    sum         double precision not null,
    unit        text,
    primary key (workout_id, name)
);

create table track_chunk (
    id           uuid        primary key,
    workout_id   uuid        not null references workout (id) on delete cascade,
    sequence     integer     not null,
    chunk_count  integer     not null,
    is_final     boolean     not null,
    start_at     timestamptz,
    end_at       timestamptz,
    received_at  timestamptz not null,
    constraint uq_track_chunk_workout_sequence unique (workout_id, sequence)
);

create table workout_event (
    id          bigint generated by default as identity primary key,
    workout_id  uuid not null references workout (id) on delete cascade,
    chunk_id    uuid references track_chunk (id) on delete cascade,
    type        text,
    start_at    timestamptz,
    end_at      timestamptz,
    metadata    jsonb
);

create index idx_workout_event_workout_start on workout_event (workout_id, start_at);

create table route_point (
    id                      bigint generated by default as identity primary key,
    workout_id              uuid             not null references workout (id) on delete cascade,
    chunk_id                uuid             not null references track_chunk (id) on delete cascade,
    t                       timestamptz,
    lat                     double precision not null,
    lon                     double precision not null,
    altitude_m              double precision not null,
    ellipsoidal_altitude_m  double precision not null,
    horizontal_accuracy_m   double precision not null,
    vertical_accuracy_m     double precision not null,
    speed_mps               double precision not null,
    speed_accuracy_mps      double precision not null,
    course_deg              double precision not null,
    course_accuracy_deg     double precision not null
);

create index idx_route_point_workout_t on route_point (workout_id, t);

create table series_point (
    id          bigint generated by default as identity primary key,
    workout_id  uuid             not null references workout (id) on delete cascade,
    chunk_id    uuid             not null references track_chunk (id) on delete cascade,
    metric      text,
    start_at    timestamptz,
    end_at      timestamptz,
    value       double precision not null
);

create index idx_series_point_workout_metric_start on series_point (workout_id, metric, start_at);
