spring.application.name=basecamp

spring.datasource.url=jdbc:postgresql://localhost:5432/basecamp
spring.datasource.username=basecamp
spring.datasource.password=basecamp

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

spring.jackson.property-naming-strategy=SNAKE_CASE
spring.jackson.deserialization.fail-on-null-for-primitives=false
